name: Clojure CI

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        java-version: [ 21 ]
        distribution: [ temurin ]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: ${{ matrix.distribution }}
        
    - name: Install Leiningen on Windows
      if: runner.os == 'Windows'
      run: |
        choco install lein
        
    - name: Install Leiningen on Mac
      if: runner.os == 'macOS'
      run: |
        brew update
        brew install lein

    - name: Install dependencies
      run: lein deps

    - name: Run tests
      run: lein test
